services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    hostname: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd123!"
      TZ: "Asia/Taipei"
      MSSQL_COLLATION: "Chinese_Taiwan_Stroke_CI_AS"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P StrongP@ssw0rd123! -C -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

volumes:
  mssql_data: